# <span style="color:red; font-size:25px"> DATASCI 151 - Quiz #5 </span>

<font size = "4" >
This quiz is open book 

<br>

- You <span style="color:red"> CAN </span> use all material from the course repo

- You should <span style="color:red"> NOT </span> use other resources outside the course repo.

- You should <span style="color:red"> NOT </span> collaborate with other students

<!-- - This is a graded quiz. Use of LLMs or any AI tools is <span style="color:red"> NOT ALLOWED. </span> -->

- AI assistance is <span style="color:red"> NOT </span> permitted for this assignment.

- To get full credit, the code should work as intended. But try to attempt every problem - you can still receive partial credit.

<br>

Print the following string:

"I will abide by Emory's code of conduct"

In [2]:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "4">

Import any packages you would like in the cell below. Or, import them as needed later in the notebook.

In [1]:
# import packages
import pandas as pd
import numpy as np

<font size = "4">

**Q1** Recode a numeric column

<font size = "3">

- Read in the file "movies.csv" from the `quiz_data` folder, saving it as a DataFrame.

- Recode the "year" variable to create a new variable called "time_period" with the following categories. (**Both** endpoints are included in the listed categories)

    - **Silent Era**: Films made between 1917 and 1927

    - **Golden Age**: Films made between 1928 and 1949

    - **Post-War**: Films made between 1950 and 1964

    - **New Hollywood**: Films made between 1965 and 1974

    - **Blockbuster Era**: Movies made between 1975 and 2000

    - **Digital Age**: Movies made between 2001 until the present

- You must use the `pd.cut` function to recode this variable.

- Add a new column to the DataFrame called "Era" that contains this recoded variable.

In [11]:
# your code here
df = pd.read_csv("quiz_data/movies.csv")
display(df)

df["Era"] = pd.cut(
    df["Year"],
    bins = [1916, 1927, 1949, 1964, 1974, 2000, float("inf")],
    labels = ["Silent Era", "Golden Age", "Post-War", "New Hollywood", "Blockbuster Era", "Digital Age"]
)

display(df)

,Title,IMDb rating,Year,MPA rating,Genre,Director,Star Cast,MetaScore,Duration (minutes)
0,The Green Knight,6.6,2021,R,Adventure,David Lowery,Dev PatelAlicia VikanderJoel Edgerton,85.0,130.0
1,Star Wars: The Clone Wars,5.9,2008,PG,Animation,Dave Filoni,Matt Lanter,35.0,98.0
2,A Quiet Place,7.5,2018,PG-13,Drama,John Krasinski,Bryan WoodsScott BeckJohn Krasinski,82.0,90.0
3,RiffTrax: Firehead,7.6,2013,Other,Action,Bill Corbett,Daniel RadcliffeEmma WatsonRupert Grint,66.0,80.0
4,The Great Dictator,8.4,1940,G,Comedy,Charles Chaplin,Charles ChaplinPaulette GoddardJack Oakie,66.0,125.0
...,...,...,...,...,...,...,...,...,...
3890,Start the Revolution Without Me,6.4,1970,PG,Comedy,Bud Yorkin,Gene WilderDonald SutherlandHugh Griffith,66.0,90.0
3891,Mr. Malcolm's List,6.0,2022,PG,Comedy,Emma Holly Jones,Suzanne Allain,65.0,117.0
3892,Angela's Ashes,7.3,1999,R,Biography,Alan Parker,Emily WatsonRobert CarlyleJoe Breen,54.0,145.0
3893,The Grizzlies,7.5,2018,R,Biography,Miranda de Pencier,Jack AnawakFred BaileySeth Burke,69.0,102.0
3894,Frida,7.3,2002,R,Biography,Julie Taymor,Hayden HerreraClancy SigalDiane Lake,61.0,123.0

,Title,IMDb rating,Year,MPA rating,Genre,Director,Star Cast,MetaScore,Duration (minutes),Era
0,The Green Knight,6.6,2021,R,Adventure,David Lowery,Dev PatelAlicia VikanderJoel Edgerton,85.0,130.0,Digital Age
1,Star Wars: The Clone Wars,5.9,2008,PG,Animation,Dave Filoni,Matt Lanter,35.0,98.0,Digital Age
2,A Quiet Place,7.5,2018,PG-13,Drama,John Krasinski,Bryan WoodsScott BeckJohn Krasinski,82.0,90.0,Digital Age
3,RiffTrax: Firehead,7.6,2013,Other,Action,Bill Corbett,Daniel RadcliffeEmma WatsonRupert Grint,66.0,80.0,Digital Age
4,The Great Dictator,8.4,1940,G,Comedy,Charles Chaplin,Charles ChaplinPaulette GoddardJack Oakie,66.0,125.0,Golden Age
...,...,...,...,...,...,...,...,...,...,...
3890,Start the Revolution Without Me,6.4,1970,PG,Comedy,Bud Yorkin,Gene WilderDonald SutherlandHugh Griffith,66.0,90.0,New Hollywood
3891,Mr. Malcolm's List,6.0,2022,PG,Comedy,Emma Holly Jones,Suzanne Allain,65.0,117.0,Digital Age
3892,Angela's Ashes,7.3,1999,R,Biography,Alan Parker,Emily WatsonRobert CarlyleJoe Breen,54.0,145.0,Blockbuster Era
3893,The Grizzlies,7.5,2018,R,Biography,Miranda de Pencier,Jack AnawakFred BaileySeth Burke,69.0,102.0,Digital Age
3894,Frida,7.3,2002,R,Biography,Julie Taymor,Hayden HerreraClancy SigalDiane Lake,61.0,123.0,Digital Age

<font size = "4">

**Q2** Conditional Subsetting

<font size = "3">

- Continue to use the movies DataFrame from Q1 (or read it in again)

- Return a DataFrame with the **6 shortest movies** that (a) were released 2011 or later, and (b) have IMDb rating of 6.0 or greater.

**Hint**: The column containing the IMDb rating is named "IMDb rating", which would not be a valid Python variable because of the space. If this causes you trouble and you don't remember how to handle it, you could simply rename the column to "IMDb_rating".

In [37]:

df.rename("IMDb rating", "IMDb_rating")


df.query('Year >= 2011').query("'IMDb rating' >= 6.0").sort_values(by = "Duration (minutes)", ascending = False).head(6)

TypeError: DataFrame.rename() takes from 1 to 2 positional arguments but 3 were given

<font size = "4">

**Q3** Aggregating Group Statistics with Chaining

<font size = "3">

- Continue to use the movies DataFrame from Q1 (or read it in again)

- The column "MPA rating" shows whether the movie was rated R, PG-13, etc. Aggregate the following statistics for each MPA rating:

    - Mean IMDb rating

    - Median duration (in minutes)

- Sort the resulting DataFrame by mean IMDb rating in **ascending** order.

- For full credit, execute all commands on a single line by chaining

In [46]:
# your code here
df.groupby("MPA rating").agg(
    avg_imdb_rating = ("IMDb rating","mean"),
    med_duration = ("duration (minutes)","median")
).sort_values(by = "avg_imdb_rating", ascending = True)

KeyError: 'MPA rating'

<font size = "4">

**Q4** Calculate laps per minute

<font size = "3">

- Read in the file "results_cleaned.csv" from the `quiz_data` folder, saving it as a DataFrame.

- The "milliseconds" column shows the race duration for each result measured in milliseconds. Create a new column called "race_duration_minutes" where we convert the race duration to minutes by dividing each millisecond value by 60,000 (which equals $6 \times 10^4$). Equivalently, you can multiply each millisecond value by $6 \times 10^{-4}$

- Create a new column called "laps_per_minute" which is calculated by the formula: $\ \dfrac{\textrm{laps}}{\textrm{race\_duration\_minutes}}$

- Group the data by **both** "raceId" and "driverId" and calculate the **maximum laps per minutes** for each group.

- Sort the data in descending order and then extract the raceId/driverId pairs with the 5 highest laps per minute

<br>

**Hint**: For a Pandas Series, the `.sort_values()` method does **not** take the keyword "by".

In [ ]:
# your code here
df = pd.read_csv("quiz_data/results_cleaned.csv")
display(df)

df["race_duration_minutes"] = df["mill iseconds"] / 60000
df["laps_per_minute"] = df["laps"] / df["race_duration_minutes"]

df.groupby(["raceId", "driverId"]).agg(
    max_laps = ("laps_per_minute","max")
).sort_values(by = "max_laps", ascending= False).head(5)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094.0,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779.0,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797.0,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630.0,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,NaN,37,15,1:23.511,188.856,11
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,NaN,43,12,1:23.047,189.911,11
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,NaN,60,8,1:22.478,191.221,11
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,NaN,58,16,1:23.538,188.795,12
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,NaN,60,19,1:24.002,187.752,131

                 max_laps
raceId driverId
653    235       1.106920
       223       1.103572
       278       1.093937
598    238       0.976598
       182       0.972569

<font size = "4">

**Q5** Aggregate and query

<font size = "3">

- Continue to use the "results_cleaned.csv" DataFrame from Q4 (or read it in again)

- Do the following in a single line using chaining:

    - Extract the subset with raceId equal to 21.

    - Aggregate the minimum number of points and average number of points for each constructor in the subset.

    - Extract the subset of these constructors with average number of points **strictly greater than 1**

In [40]:
df = pd.read_csv("quiz_data/results_cleaned.csv")
display(df)

df.query("raceId == 21").groupby("constructorId").agg(
    min_points = ("points", "min"),
    avg_points = ("points", "mean")
).query("avg_points > 1")

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616.0,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094.0,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779.0,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797.0,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630.0,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,NaN,37,15,1:23.511,188.856,11
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,NaN,43,12,1:23.047,189.911,11
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,NaN,60,8,1:22.478,191.221,11
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,NaN,58,16,1:23.538,188.795,12
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,NaN,60,19,1:24.002,187.752,131

               min_points  avg_points
constructorId
1                     0.0         3.0
2                     0.0         2.5
6                     8.0         9.0
9                     0.0         2.0
11                    0.0         1.5

<font size = "4">

**Q6** Aggregate custom statistic

<font size = "3">

- Continue to use the DataFrame corresponding to the data in "results_cleaned.csv" (or read it in again).

- We might consider it a "bad day" for an F1 driver if they finish outside the top ten (11th or worse). Write a function that takes in a Pandas Series and returns the number of entries $ > 10$.

- Group by "driverId" and then aggregate the following statistics based on the "positionOrder" column: the average (mean) position and the number of finishes outside the top ten.

- Use your custom function for this second statistic.

- Merge the aggregated data back **into the original DataFrame**.

In [29]:
# your code here
def bad_day(position):
    return np.sum(position > 10)

df_agg = df.groupby("driverId").agg(
    avg_position = ("positionOrder", "mean"),
    num_of_finish_outside10 = ("positionOrder", bad_day)
)

df = pd.merge(df, df_agg, on = "driverId")